"""baseline schema

Revision ID: 8dc7dd5600f3
Revises: 
Create Date: 2026-04-24 13:22:22.252763

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8dc7dd5600f3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenants_name'), 'tenants', ['name'], unique=True)
    op.create_table('app_users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('keycloak_sub', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_app_users_email'), 'app_users', ['email'], unique=True)
    op.create_index(op.f('ix_app_users_keycloak_sub'), 'app_users', ['keycloak_sub'], unique=True)
    op.create_index(op.f('ix_app_users_tenant_id'), 'app_users', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_app_users_username'), 'app_users', ['username'], unique=False)
    op.create_table('contact_cards',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('relationship_type', sa.String(length=20), nullable=True),
    sa.Column('hobbies', sa.JSON(), nullable=True),
    sa.Column('interests', sa.JSON(), nullable=True),
    sa.Column('family_status', sa.String(length=100), nullable=True),
    sa.Column('birthday', sa.Date(), nullable=True),
    sa.Column('promises', sa.JSON(), nullable=True),
    sa.Column('goals', sa.JSON(), nullable=True),
    sa.Column('ambitions', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contact_cards_email'), 'contact_cards', ['email'], unique=False)
    op.create_index(op.f('ix_contact_cards_full_name'), 'contact_cards', ['full_name'], unique=False)
    op.create_index(op.f('ix_contact_cards_phone'), 'contact_cards', ['phone'], unique=False)
    op.create_index(op.f('ix_contact_cards_tenant_id'), 'contact_cards', ['tenant_id'], unique=False)
    op.create_table('contact_family_members',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('contact_id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('relation', sa.String(length=100), nullable=True),
    sa.Column('birthday', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contact_cards.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contact_family_members_contact_id'), 'contact_family_members', ['contact_id'], unique=False)
    op.create_table('contact_interactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('contact_id', sa.UUID(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('channel', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('promises', sa.JSON(), nullable=True),
    sa.Column('mentions', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contact_cards.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contact_interactions_contact_id'), 'contact_interactions', ['contact_id'], unique=False)
    op.create_table('contact_links',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('contact_id_a', sa.UUID(), nullable=False),
    sa.Column('contact_id_b', sa.UUID(), nullable=False),
    sa.Column('relationship_type', sa.String(length=50), nullable=False),
    sa.Column('context', sa.Text(), nullable=True),
    sa.Column('is_directed', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['contact_id_a'], ['contact_cards.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['contact_id_b'], ['contact_cards.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_contact_links_contact_id_a'), 'contact_links', ['contact_id_a'], unique=False)
    op.create_index(op.f('ix_contact_links_contact_id_b'), 'contact_links', ['contact_id_b'], unique=False)
    op.create_index(op.f('ix_contact_links_tenant_id'), 'contact_links', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_contact_links_tenant_id'), table_name='contact_links')
    op.drop_index(op.f('ix_contact_links_contact_id_b'), table_name='contact_links')
    op.drop_index(op.f('ix_contact_links_contact_id_a'), table_name='contact_links')
    op.drop_table('contact_links')
    op.drop_index(op.f('ix_contact_interactions_contact_id'), table_name='contact_interactions')
    op.drop_table('contact_interactions')
    op.drop_index(op.f('ix_contact_family_members_contact_id'), table_name='contact_family_members')
    op.drop_table('contact_family_members')
    op.drop_index(op.f('ix_contact_cards_tenant_id'), table_name='contact_cards')
    op.drop_index(op.f('ix_contact_cards_phone'), table_name='contact_cards')
    op.drop_index(op.f('ix_contact_cards_full_name'), table_name='contact_cards')
    op.drop_index(op.f('ix_contact_cards_email'), table_name='contact_cards')
    op.drop_table('contact_cards')
    op.drop_index(op.f('ix_app_users_username'), table_name='app_users')
    op.drop_index(op.f('ix_app_users_tenant_id'), table_name='app_users')
    op.drop_index(op.f('ix_app_users_keycloak_sub'), table_name='app_users')
    op.drop_index(op.f('ix_app_users_email'), table_name='app_users')
    op.drop_table('app_users')
    op.drop_index(op.f('ix_tenants_name'), table_name='tenants')
    op.drop_table('tenants')
    # ### end Alembic commands ###
