"""add uq_contact_links_pair_type

Revision ID: e8821371d1f5
Revises: 8dc7dd5600f3
Create Date: 2026-04-24 13:47:49.382101

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8821371d1f5'
down_revision: Union[str, Sequence[str], None] = '8dc7dd5600f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_contact_links_pair_type', 'contact_links', ['contact_id_a', 'contact_id_b', 'relationship_type'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_contact_links_pair_type', 'contact_links', type_='unique')
    # ### end Alembic commands ###
